### ISSUE TITLE
Failed to execute 'stop' on 'MediaRecorder': The MediaRecorder's state is 'inactive'

### ISSUE THREAD

**Issue by sunniejai** [Ziggeo/react-ziggeo#102]
On react-ziggeo 4.5.0. Getting this error when pressing stop. 

This only started happening recently. Code was working for a while before this. Did something change?

Seems to happen on Chrome. Firefox is working properly.

Uncaught DOMException: Failed to execute 'stop' on 'MediaRecorder': The MediaRecorder's state is 'inactive'.
    at constructor.stop (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:303148)
    at constructor.destroy (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:302337)
    at o._unboundMedia (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:340226)
    at o.unbindMedia (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:314542)
    at constructor._unbindMedia (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:332658)
    at constructor.unbindMedia (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:277556)
    at o._unbindMedia (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:1420765)
    at t._hasStopped (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:1390147)
    at t._hasStopped (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:2040344)
    at t.eval (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:1389589)
    at Promise.triggerResult (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:50277)
    at Promise.triggerResult (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:50419)
    at Promise.asyncSuccess (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:50860)
    at constructor.eval (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:335599)
    at constructor.eval (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:58444)
    at constructor.eval (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:24496)
    at o._invokeCallback (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:56684)
    at o.__invokeCallback (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:56565)
    at o.__call_event_object (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:56943)
    at o.eval (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:58826)
    at o.eval (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:54669)
    at o._iterate (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:55314)
    at o.iterate (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:54638)
    at o.eval (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:58804)
    at Object.iter (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:27673)
    at o.trigger (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:58724)
    at o._dataAvailable (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:324298)
    at o.eval (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:340160)
    at constructor._invokeCallback (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:56684)
    at constructor.__invokeCallback (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:56565)
    at constructor.__call_event_object (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:56943)
    at o.eval (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:58826)
    at o.eval (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:54669)
    at o._iterate (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:55314)
    at o.iterate (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:54638)
    at constructor.eval (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:58804)
    at Object.iter (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:27673)
    at constructor.trigger (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:58724)
    at constructor._dataStop (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:303617)
    at MediaRecorder.eval (webpack-internal:///../../node_modules/react-ziggeo/build/index.js:11928:24315)

**Comment by sambua** [comment]
Hello @sunniejai , we've published a new release 2.42.2 where it's fixed. 
As it's not stable for now we're not upgraded SDKs. But you always can do it manually. Here's documentation where you can upgrade to the newest release https://github.com/Ziggeo/react-ziggeo#upgrade-ziggeo-sdk

**Comment by sunniejai** [comment]
Any idea how long it would take for it to be stable before I manually upgrade?

**Comment by KBbitsP** [comment]
> Any idea how long it would take for it to be stable before I manually upgrade?

Hi @sunniejai The R42 revision has been made the stable release. So if you are using the Stable tag, then it will automatically point to R42.
